manipulator:
  #kinematics_solver: ur_kinematics/UR3KinematicsPlugin
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  #kinematics_solver: bio_ik/BioIKKinematicsPlugin
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 1
  #minimal_displacement_weight: 1
  #center_joints_weight: 1
  #avoid_joint_limits_weight: 1
  #solve_type: Manipulation1
